# Generated by Django 4.1.2 on 2022-11-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='password',
            field=models.TextField(default='123456', max_length=64, verbose_name='密码'),
        ),
    ]
