# Generated by Django 4.1.2 on 2022-11-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created_id',
            field=models.IntegerField(default=0, verbose_name='创建者'),
        ),
    ]
