# Generated by Django 4.1.2 on 2022-11-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_id_designer_des_id_and_more'),
        ('artwork', '0004_alter_work_created_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='id',
            new_name='wrk_id',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='name',
            new_name='wrk_name',
        ),
        migrations.AlterField(
            model_name='work',
            name='created_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.designer'),
        ),
    ]
