# Generated by Django 4.1.2 on 2022-11-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBundles',
            fields=[
                ('ab_id', models.AutoField(primary_key=True, serialize=False, verbose_name='作品ID')),
                ('ab_name', models.CharField(default='Null', max_length=40, verbose_name='名字')),
                ('ab_md5', models.TextField(default='md5', max_length=400, verbose_name='ab包的md5')),
                ('ab_cp', models.TextField(default='0.0.0', max_length=400, verbose_name='版本')),
                ('description', models.TextField(default='无', max_length=400, verbose_name='介绍')),
                ('mark', models.TextField(default='默认标注', max_length=400, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': 'ab包信息表',
                'verbose_name_plural': 'ab包信息表',
                'ordering': ['-created_at'],
            },
        ),
    ]
