# Generated by Django 4.1.2 on 2022-11-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetbundle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseCopyRight',
            fields=[
                ('rcp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='版本ID')),
                ('rcp_name', models.CharField(default='CopyRight 1.0', max_length=40, verbose_name='版本名字')),
                ('rcp_content', models.TextField(default='0.0.0', max_length=400, verbose_name='版本号')),
                ('description', models.TextField(default='无', max_length=400, verbose_name='介绍')),
                ('mark', models.TextField(default='默认标注', max_length=400, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '发布版本信息表',
                'verbose_name_plural': '发布版本信息表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='assetbundles',
            name='ab_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ab包ID'),
        ),
        migrations.AlterField(
            model_name='assetbundles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='assetbundles',
            name='ab_cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetbundle.releasecopyright'),
        ),
    ]
